import { test, expect } from "./fixtures";
import { createRoom } from "./api";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";

async function connect(base: string) {
  const client = new Client({ name: "botchat-test", version: "1.0.0" });
  await client.connect(new StreamableHTTPClientTransport(new URL(`${base}/mcp`)));
  return client;
}

const textOf = (r: any) => r.content.map((c: any) => c.text).join("\n");

test("shows a file attached to a message", async ({ page, server }) => {
  const room = await createRoom(server.url, "files");
  await page.goto(`${server.url}/rooms/${room.id}?as=tom`);
  await page.getByLabel("Attach a file").setInputFiles({
    name: "notes.txt",
    mimeType: "text/plain",
    buffer: Buffer.from("the quick brown fox"),
  });
  await page.getByLabel("Message").fill("here are my notes");
  await page.getByRole("button", { name: "Send" }).click();
  await expect(page.getByTestId("transcript")).toContainText("notes.txt");
});

test("serves the attached bytes back unchanged", async ({ page, server }) => {
  const room = await createRoom(server.url, "bytes");
  await page.goto(`${server.url}/rooms/${room.id}?as=tom`);
  await page.getByLabel("Attach a file").setInputFiles({
    name: "notes.txt",
    mimeType: "text/plain",
    buffer: Buffer.from("the quick brown fox"),
  });
  await page.getByLabel("Message").fill("read this");
  await page.getByRole("button", { name: "Send" }).click();
  const href = await page
    .getByTestId("transcript")
    .getByRole("link", { name: "notes.txt" })
    .getAttribute("href");
  const res = await page.request.get(new URL(href!, server.url).toString());
  expect(await res.text()).toBe("the quick brown fox");
});

test("keeps the attachment after a restart", async ({ page, server }) => {
  const room = await createRoom(server.url, "durable files");
  await page.goto(`${server.url}/rooms/${room.id}?as=tom`);
  await page.getByLabel("Attach a file").setInputFiles({
    name: "keeps.txt",
    mimeType: "text/plain",
    buffer: Buffer.from("still here"),
  });
  await page.getByLabel("Message").fill("saved");
  await page.getByRole("button", { name: "Send" }).click();
  await expect(page.getByTestId("transcript")).toContainText("keeps.txt");

  await server.restart();
  await page.goto(`${server.url}/rooms/${room.id}?as=tom`);
  const href = await page
    .getByTestId("transcript")
    .getByRole("link", { name: "keeps.txt" })
    .getAttribute("href");
  const res = await page.request.get(new URL(href!, server.url).toString());
  expect(await res.text()).toBe("still here");
});

test("lets a bot read a file a person attached", async ({ page, server }) => {
  const room = await createRoom(server.url, "shared with a bot");
  await page.goto(`${server.url}/rooms/${room.id}?as=tom`);
  await page.getByLabel("Attach a file").setInputFiles({
    name: "keeps.txt",
    mimeType: "text/plain",
    buffer: Buffer.from("the quick brown fox"),
  });
  await page.getByLabel("Message").fill("have a look");
  await page.getByRole("button", { name: "Send" }).click();
  await expect(page.getByTestId("transcript")).toContainText("keeps.txt");

  const client = await connect(server.url);
  const listed = textOf(
    await client.callTool({ name: "list_attachments", arguments: { room_id: room.id } }),
  );
  expect(listed).toContain("keeps.txt");

  const blobId = listed.match(/[0-9a-f]{64}/)![0];
  const read = textOf(
    await client.callTool({ name: "read_attachment", arguments: { blob_id: blobId } }),
  );
  expect(read).toContain("the quick brown fox");
  await client.close();
});

test("shows a file a bot attached", async ({ page, server }) => {
  const room = await createRoom(server.url, "sent by a bot");
  await page.goto(`${server.url}/rooms/${room.id}?as=tom`);
  await expect(page.getByTestId("transcript")).toHaveAttribute("data-connection", "open");

  const uploaded = await (
    await fetch(`${server.url}/api/blobs`, {
      method: "POST",
      headers: { "content-type": "text/plain" },
      body: "generated by a bot",
    })
  ).json();

  const client = await connect(server.url);
  await client.callTool({
    name: "post_message",
    arguments: {
      room_id: room.id,
      author: "ada",
      body: "here is the report",
      attachments: [{ blob_id: uploaded.id, filename: "report.txt" }],
    },
  });

  const href = await page
    .getByTestId("transcript")
    .getByRole("link", { name: "report.txt" })
    .getAttribute("href");
  const res = await page.request.get(new URL(href!, server.url).toString());
  expect(await res.text()).toBe("generated by a bot");
  await client.close();
});

test("refuses a message whose attachment was never uploaded", async ({ server }) => {
  const room = await createRoom(server.url, "missing blob");
  const res = await fetch(`${server.url}/api/rooms/${room.id}/messages`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      author: "tom",
      body: "attached to nothing",
      attachments: [{ blobId: "0".repeat(64), filename: "ghost.txt" }],
    }),
  });
  expect(res.status).toBe(404);

  const history = await (await fetch(`${server.url}/api/rooms/${room.id}/messages`)).json();
  expect(history).toHaveLength(0);
});
