export const RED_PNG_48x32 =
  "iVBORw0KGgoAAAANSUhEUgAAADAAAAAgCAIAAADbtmxLAAAANklEQVR4nO3OQQ0AAAgEINPZP4BhbOH5" +
  "YCMANd2vVHwgJCQklB4ICQkJpQdCQkJC6YGQkNCxBRGRcHmJl8UqAAAAAElFTkSuQmCC";

export const WIDE_PNG_1200x40 =
  "iVBORw0KGgoAAAANSUhEUgAABLAAAAAoCAIAAABhOZSlAAAA4klEQVR42u3XMQ0AAAgEsZeCNOQiCxVMNKmC" +
  "2y7VAwAAwEORAAAAwBACAABgCAEAADCEAAAAGEIAAAAMIQAAAIYQAAAAQwgAAIAhBAAAwBACAABgCAEAADCE" +
  "AAAAGEIAAAAMIQAAAIYQAAAAQwgAAIAhBAAAwBACAABgCAEAADCEAAAAGEIAAAAMIQAAAIYQAAAAQwgAAGAI" +
  "AQAAMIQAAAAYQgAAAAwhAAAAhhAAAABDCAAAgCEEAADAEAIAAGAIAQAAMIQAAAAYQgAAAAwhAAAAhhAAAABD" +
  "CAAAgCEEAADgxgLB6UoRiAUkegAAAABJRU5ErkJggg==";

export const redPng = () => Buffer.from(RED_PNG_48x32, "base64");

export const widePng = () => Buffer.from(WIDE_PNG_1200x40, "base64");
